### ISSUE TITLE
Possibility of transferring ownership of the iso name in crates.io

### ISSUE THREAD

**Issue by rbalicki2** [superwhiskers/iso#1]
Howdy!

I'm the author of isograph.dev, which is a framework for building React apps powered by GraphQL data. It heavily leverages a Rust compiler. Would you open to transferring ownership of the "iso" name on crates.io to Isograph?

It would be super cool to have a punchier name for the project.

Anyway, if you're interested, you can find out more about the project here https://www.youtube.com/watch?v=gO65JJRqjuc. Feel free to also shoot me an email at robert.balicki@gmail.com.

Cheers!
Robert

**Comment by superwhiskers** [comment]
thank you for asking but no

**Comment by rbalicki2** [comment]
Okay, cheers!
